export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'
// Alarms
export const FETCH_ALARMS = 'FETCH_ALARMS'
export const FETCH_ALARM = 'FETCH_ALARM'
export const ADD_ALARM = 'ADD_ALARM'
export const REMOVE_ALARM = 'REMOVE_ALARM'
export const UPDATE_ALARM = 'UPDATE_ALARM'
export const ON_OFF_ALARM = 'ON_OFF_ALARM'
